name: deploy_frontend

on:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t sirijupally/reactjs-app:latest --build-arg REACT_APP_MODE_ENV='production' --build-arg VITE_API_URL_SERVER='${{ secrets.VITE_API_SERVER_URL }}' --build-arg VITE_ADMIN_PASSWORD='${{ secrets.ADMIN_PASSWORD }}' .
      - name: Push Docker Image
        run: docker push sirijupally/reactjs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull sirijupally/reactjs-app:latest

      - name: Stop and remove existing container
        run: |
          docker stop reactjs-app-container || true
          docker rm reactjs-app-container || true

      - name: Deploy to EC2 with Restart Policy
        run: >
          docker run -d 
          --restart unless-stopped 
          -p 80:80    
          --name reactjs-app-container sirijupally/reactjs-app:latest
          
      - name: Clean up old images
        run: docker image prune -f